### ISSUE TITLE
about confirm save untitled workspace

### ISSUE THREAD

**Issue by AlanQtten** [tanchekwei/compare-view#6]
in the latest vscode (v1.86.0), there is an new setting called `window.confirmSaveUntitledWorkspace`, but somehow it's not working in compare view, also the `checkbox` in [this doc](https://code.visualstudio.com/updates/v1_86#_workbench) is not showing correctly

**Comment by tanchekwei** [comment]
> there is an new setting called `window.confirmSaveUntitledWorkspace`, but somehow it's not working in compare view

Could you please provide more details on what behavior you expect to see from that setting when using compare view? Also, a short video demonstrating the problem along with steps to reproduce would be very helpful.

> also the checkbox in [this doc](https://code.visualstudio.com/updates/v1_86#_workbench) is not showing correctly

could you specify which checkbox in the documentation you are referring to? A screenshot highlighting the checkbox would help.

**Comment by AlanQtten** [comment]
thx for reply
I hope when I set `window.confirmSaveUntitledWorkspace` to true and close compare view window, there won't be a question that ask me if I want to save 
![image](https://github.com/tanchekwei/compare-view/assets/51439181/83f55e54-c5d9-4a1c-b050-89972aaabb48)

and there is the checkbox
![image](https://github.com/tanchekwei/compare-view/assets/51439181/b86b0c9b-b30b-4f9a-882a-9da22e7c7d5f)

**Comment by tanchekwei** [comment]
Based on what I’ve understood from [the release note](https://code.visualstudio.com/updates/v1_86#_allow-closing-untitled-workspaces-without-confirmation), the `window.confirmSaveUntitledWorkspace` setting is specifically applicable to untitled workspaces, and not to untitled files

As of now, there is no option to bypass the confirmation dialog for closing untitled files.

**Comment by AlanQtten** [comment]
ok, thx anyway

**Comment by AlanQtten** [comment]
> Based on what I’ve understood from [the release note](https://code.visualstudio.com/updates/v1_86#_allow-closing-untitled-workspaces-without-confirmation), the `window.confirmSaveUntitledWorkspace` setting is specifically applicable to untitled workspaces, and not to untitled files
> 
> As of now, there is no option to bypass the confirmation dialog for closing untitled files.


ok, thx anyway
